 --CREATE DATABASE AULA_DS;

--USE AULA_DS;


CREATE TABLE PROFESSORES(
ID INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(50) NOT NULL,
APELIDO VARCHAR(15) NOT NULL
)

CREATE TABLE SALAS(
ID INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(30) NOT NULL,
NUMERO_COMPUTADORES INT NOT NULL,
NUMERO_CADEIRAS INT NOT NULL,
IsLab BIT,
Disponivel BIT NOT NULL
)

CREATE TABLE DISCIPLINAS(
Id INT PRIMARY KEY IDENTITY(1,1),
Nome VARCHAR(60) NOT NULL,
Sigla VARCHAR(8) NOT NULL
)

CREATE TABLE CURSOS(
Id INT PRIMARY KEY IDENTITY(1,1),
Nome Varchar(40),
turno varchar(10),
sigla varchar(10)
)

CREATE TABLE CURSO_DISCIPLINA(
Id INT PRIMARY KEY IDENTITY(1,1),
Periodo VARCHAR(15),
DisciplinaID INT NOT NULL,
CursoId INT NOT NULL
CONSTRAINT FK_DISCIPLINA FOREIGN KEY (DisciplinaID) REFERENCES Disciplinas(Id),
CONSTRAINT FK_CURSOS FOREIGN KEY (CursoId) REFERENCES Cursos(Id)
)